version: "2"
run:
  issues-exit-code: 1
  tests: false
output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - decorder
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errcheck
    - errname
    - exhaustive
    - gosec
    - govet
    - importas
    - ineffassign
    - misspell
    - prealloc
    - promlinter
    - sloglint
    - sqlclosecheck
    - staticcheck
    - testableexamples
    - testifylint
    - tparallel
    - unconvert
    - unused
    - wastedassign
    - whitespace
    - zerologlint
  settings:
    errcheck:
      exclude-functions:
        - fmt.*
        - (go.uber.org/zap/zapcore.ObjectEncoder).AddObject
        - (go.uber.org/zap/zapcore.ObjectEncoder).AddArray
    exhaustive:
      ignore-enum-types: reflect.Kind|svc.Cmd
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gosec
        text: G115
      - linters:
          - gosec
        text: G107
      - linters:
          - gosec
        text: G203
      - linters:
          - gosec
        text: G204
      - linters:
          - gosec
        path: modules/caddyhttp/reverseproxy/selectionpolicies.go
        text: G404
      - linters:
          - gosec
        path: modules/caddyhttp/reverseproxy/streaming.go
        text: G404
      - linters:
          - dupl
        path: modules/logging/filters.go
      - linters:
          - dupl
        path: modules/caddyhttp/matchers.go
      - linters:
          - dupl
        path: modules/caddyhttp/vars.go
      - linters:
          - errcheck
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/caddyserver/caddy/v2/cmd)
        - prefix(github.com/caddyserver/caddy)
      custom-order: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
